apiVersion: v1
kind: Service
metadata:
  name: search-engine
  namespace: default
spec:
  type: NodePort
  selector:
    app: search-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080